### ISSUE TITLE
Source of RRULES for Easter

### ISSUE THREAD

**Issue by chiriones** [sappjw/calendars#1]
Hello @sappjw,

What is the source of the RRULES for the events that are Easter ie where can I reference them? Is that something that you created or is it based on an article you read somewhere? Whatever the source is, I would like to know it.

I'm afraid to use the calendar until I understand the reasoning behind the calculations better.

It would be nice if the source or credit was included for all of the RRULE calculations in the Readme or some other document in the repository, whether it was you or based on some other work.

Thank you.

**Comment by sappjw** [comment]
I created the rules based on [the Easter Wikipedia](https://en.wikipedia.org/wiki/Easter) article.  As far as I know, they were correct for the few years surrounding this year.  If you find a problem, please feel free to open another issue.  I'll consider adding this information to the README when I have time.  Thanks for the feedback!

**Comment by chiriones** [comment]
Thank you @sappjw! Yours is the first example I had seen using ical rrule. Many of the articles I had seen about calculating Easter use an algorithm that can't be used directly in ical, like this article: http://aa.usno.navy.mil/faq/docs/easter.php.  I appreciate you creating them in ical.

**Comment by sappjw** [comment]
Thanks! I hoped it would be useful.  See also [this article](https://en.wikipedia.org/wiki/Computus) on computing the dates.  I updated the README in 50a0785.

**Comment by chiriones** [comment]
Thanks for the update and link. I made a Google Sheet to verify all of the dates in the RRULE for Easter using the formula from the section on the Anonymous Gregorian Algorithm in the Wikipedia Computus article. http://bit.ly/1OxDMvg It looks like all 19 sets of year ranges from the sheet matches the dates that you have in the 19 rules for Easter. What an interesting way to go about it, just looking at the results of the formula and finding patterns and figuring out the rule from there. Did you use a spreadsheet or was there some other mathematical way that you figured out the rules?

I experimented on another spreadsheet with longer ranges of years and the resulting dates seem to group fine but the list of possible dates gets longer as the years increase. What limitations did you see that made you want to stop at the year 2184? Is it that iCal will probably be replaced by the year 2184? :)

**Comment by sappjw** [comment]
In the [Gregorian calendar section](https://en.wikipedia.org/wiki/Computus#Gregorian_calendar) you can see:

> Easter Sunday is the Sunday following the paschal full moon date.

So the trick is to write code to reference the first Sunday after the paschal full moon date, which is the same day in each relative year in the "Metonic cycle" of 19 years.  That's what each RRULE does.  For example: in 1900 and every 19th year thereafter, the paschal full moon date is on April 14.  The Sunday after this can only be one of 7 choices.

In the same section (emphasis mine):

> A formula for paschal full moon date can be derived from the table and is valid from **1900 to 2199**.

So two reasons for ending in 2199: I'm not sure if this trend continues past 2199 and this calendar will probably be obsolete by then :)  There's plenty of time for the next person to figure it out!
